server:
  port: 8089

joinfaces:
  faces:
    project-stage: development
  primefaces:
    theme: saga

spring:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

dashboard:
  filters:
    - name: "שפיות"
      items:
        - title: "שפיות TS"
          baseDir: "G:/Automation/Execution Reports/Tamar/TS/Regression"
          dirNameRegex: ".*Sanity_TS$"
        - title: "שפיות PR"
          baseDir: "G:/Automation/Execution Reports/Tamar/PR/Regression"
          dirNameRegex: ".*Sanity_PR$"
        - title: "שפיות HD"
          baseDir: "G:/Automation/Execution Reports/Tamar/HD/Regression"
          dirNameRegex: ".*Sanity_HD$"

#    - name: "און ליין"
#      items:
#        - title: "און ליין"
#          baseDir: "D:/Runs/Online/Regression"
#          dirNameRegex: "^Sanity_Online.*"
#
#    - name: "שקד"
#      items:
#        - title: "שקד"
#          baseDir: "D:/Runs/Shaked/Regression"
#          dirNameRegex: "^Sanity.*"

